blank_issues_enabled: false
contact_links:
  - name: ğŸ’¡ Ask for a new feature or enhancement
    url: https://github.com/flexxibleit/fa-community/discussions/categories/ideas
    about: Submit new ideas and vote for existing ones.
  - name: ğŸ”§ FlexxAnalyzer Community Support
    url: https://github.com/flexxibleit/fa-community/discussions
    about: Please ask and answer questions here.
  - name: ğŸ” Report a security problem
    url: https://docs.flexxanalyzer.com/en/trust-center/security/contact-us
    about: Please report security vulnerabilities here.
